### ISSUE TITLE
Using IQKeyboardReturnKeyHandler but not working

### ISSUE THREAD

**Issue by x4080** [tjvantoll/nativescript-IQKeyboardManager#1]
Hi TJ, first of all good job for the plugin. I wondered how to use the IQKeyboardReturnKeyHandler in the 
https://github.com/hackiftekhar/IQKeyboardManager#keyboard-return-key-handling-

So that the "return" key can also move like we click "next" button, I tried 
@pageloaded :
returnKeyHandler = IQKeyboardReturnKeyHandler.alloc().initWithViewController(page.ios);

but seems nothing is changes, do you have a tip ?

Thanks (its not really an issue, more like a question)

**Comment by tjvantoll** [comment]
Hey @x4080,

You might be interested in the implementation I have in Groceries. I have two fields (email and password). I then use the `returnKeyType` and `returnPress` attributes to let the user 1) Click next to go from email to password, and 2) click “Return” to submit the form from the second, password, field.

Here are the relevant files:

* [login.xml](https://github.com/NativeScript/sample-Groceries/blob/64e3e2b8db102a8c9e391b384b422b2b32adda89/app/views/login/login.xml#L10-L11)
* [login.js](https://github.com/NativeScript/sample-Groceries/blob/64e3e2b8db102a8c9e391b384b422b2b32adda89/app/views/login/login.js#L44-L45)

Let me know if this helps.

**Comment by x4080** [comment]
Thanks tj, it helps but maybe if we have lots of fields it better to automate it. Do you know why it doesn't work in ns?

**Comment by tjvantoll** [comment]
Actually after playing with this some `IQKeyboardReturnKeyHandler.alloc().initWithViewController(page.ios);` does seem to work. In my two `<TextField>` page, when the first text field gets focus, the keyboard automatically uses a “Next” return key that moves focus to the second text field. You’re not seeing that behavior?

**Comment by x4080** [comment]
Hm that is strange and good news actually, you call it at pageloaded too? Ill try again and try figure out whats wrong

**Comment by tjvantoll** [comment]
Yep I just had it at the started of my page’s `loaded` event handler.

**Comment by x4080** [comment]
TJ, I found the culprit, I was using it in a dynamically loaded component, and turns out that it have its own viewcontroller, so I just "bind" it to the component's view controller and works perfectly

Thanks for the help

**Comment by tjvantoll** [comment]
Ah, ok that makes sense. And no problem! I’ll close this issue for now. Let me know if you need anything else.

**Comment by x4080** [comment]
Hi again TJ, I wondered if your test still work on the observable assigned to the textfield ? Because I just realized that my observable is not changing any more, maybe thats because the event is forwarded to IQKeyboardManager ?

Thanks

**Comment by tjvantoll** [comment]
Hey @x4080,

Nope I haven’t seen that. Groceries uses Observables throughout and I haven’t had a problem. If you can post a small code sample I could try to help see what’s up.
