### ISSUE TITLE
Error Run Ios

### ISSUE THREAD

**Issue by loscabres** [tjvantoll/nativescript-IQKeyboardManager#10]
When I use the plugin in my nativescript project then I try to run this error appears

Processing node_modules failed. Error: Command sandbox-pod failed with exit code 1 Error output: 
 /Users/leo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/config.rb:150:in `pwd': Operation not permitted - getcwd (Errno::EPERM)
    from /Users/leo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/config.rb:150:in`installation_root'
    from /Users/leo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/config.rb:212:in `podfile_path'
    from /Users/leo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface/error_report.rb:104:in`markdown_podfile'
    from /Users/leo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface/error_report.rb:29:in `report'
    from /Users/leo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:64:in`report_error'
    from /Users/leo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/claide-1.0.0/lib/claide/command.rb:396:in `handle_exception'
    from /Users/leo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/claide-1.0.0/lib/claide/command.rb:337:in`rescue in run'
    from /Users/leo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/claide-1.0.0/lib/claide/command.rb:325:in `run'
    from /Users/leo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:50:in`run'
    from /Users/leo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/bin/pod:55:in `<main>'

**Comment by tjvantoll** [comment]
Hi @loscabres,

So sorry that we missed this issue when it came in. We just released a new version of this plugin. If you’re still having problems please let us know and we can look into this.
