### ISSUE TITLE
Prevent IQKeyBoardManager from hiding the Action Bar

### ISSUE THREAD

**Issue by Daxito** [tjvantoll/nativescript-IQKeyboardManager#11]
Hi,
Is there a way to prevent IQKeyBoardManager from hiding the Action Bar? When it opens the KeyBoard it pushes up the Action Bar and user cannot use the Action Bar any more until they hide the keyboard somehow (Sometimes the keyboard does not have the "Close Keyboard" key and user is stuck) 

Thanks

**Comment by jboeijenga** [comment]
+1

**Comment by Yamilquery** [comment]
+1

I'm also interested in how to hide the action bar and the "auto-suggestions"...

**Comment by danieljohngomez** [comment]
+1

**Comment by Daxito** [comment]
+1
Today a coworker noticed that you can still scroll to the action bar while the keyboard is opened, so that works for us! I will close this as this would require a change on the original pod I think.

**Comment by pap5508** [comment]
@Daxito : How ? could you please give some hint to handle this..?

**Comment by Daxito** [comment]
@pap5508 Actually, it does not work on all devices just like that, but we noticed that if you wrap your form with a ScrollView then the keyboard does not cover the text field, try that.

**Comment by cerireyhan** [comment]
Hi, is anyone able to do this?
