### ISSUE TITLE
nativescript-IQKeyboardManager issue publish store

### ISSUE THREAD

**Issue by marcossaore** [tjvantoll/nativescript-IQKeyboardManager#12]
I 'm having problems publishing an app with this plugin, it does not generate any compilation error , but when trying to put it in the store , an error appears : " bundle identifier " , what should I do ?

**Comment by tjvantoll** [comment]
Hi @marcossaore,

Sorry we missed this issue when you submitted it. We just released an updated version of this plugin, so if you’re still having this problem please let us know.
