### ISSUE TITLE
Keyboard hidden

### ISSUE THREAD

**Issue by glueckandi** [tjvantoll/nativescript-IQKeyboardManager#13]
With Nativescript 2.3.0 and Angular 2 Final, i get no error at compile or run time,
but the keyboard is hidden.
I can only see the 'DONE' button.
Screenshot attached.

![keyboard](https://cloud.githubusercontent.com/assets/1733670/18645803/fad55ac4-7eae-11e6-8af1-17dad88b801f.png)

[package.json.zip](https://github.com/tjvantoll/nativescript-IQKeyboardManager/files/480912/package.json.zip)

**Comment by 3rror404** [comment]
That's probably because the simulator thinks you have a bluetooth keyboard attached. 

Hardware > Keyboard > Connect Hardware Keyboard

**Comment by EddyVerbruggen** [comment]
What @3rror404 says is correct, this can be closed.

**Comment by tjvantoll** [comment]
Closing. If anyone is still having issues with this please comment and let us know.
