### ISSUE TITLE
Framework not found IQKeyboardManager

### ISSUE THREAD

**Issue by Leo-lay** [tjvantoll/nativescript-IQKeyboardManager#14]
I added the framework can be used normally, but when I used xcode archive will appear Framework not found IQKeyboardManager

follow the all error
`
Showing Recent Messages
(null): Directory not found for option '-F/Users/adi/Library/Developer/Xcode/DerivedData/gp2mobile-agfjexrcfkohcdhkboykowbaxfyg/Build/Intermediates/ArchiveIntermediates/gp2mobile/BuildProductsPath/Release-iphoneos/IQKeyboardManager'

(null): Directory not found for option '-F/Users/adi/Library/Developer/Xcode/DerivedData/gp2mobile-agfjexrcfkohcdhkboykowbaxfyg/Build/Intermediates/ArchiveIntermediates/gp2mobile/BuildProductsPath/Release-iphoneos/MBProgressHUD'

(null): Framework not found IQKeyboardManager

`

had any one fixed it？

**Comment by davidloiret** [comment]
Any update?

**Comment by jwuliger** [comment]
Hello I am having the exact same problem.

**Comment by tjvantoll** [comment]
Hi all,

Sorry for the late reply here ☹️ 

We just pushed out a new version of this plugin. If you’re still having problems please let us know so we can look into this.
