### ISSUE TITLE
Hide the "done" button, using Angular 2

### ISSUE THREAD

**Issue by Yamilquery** [tjvantoll/nativescript-IQKeyboardManager#15]
I'm trying to hide the "done" button on my Angular 2 app using this:

`myInput.ios.inputAccessoryView = UIView.alloc().init();`

But, I'm getting this error:

`Cannot find name 'UIView'`

**Comment by Green-Cat** [comment]
@tjvantoll

**Comment by triniwiz** [comment]
place 👉  `declare var UIView:any;` at the top of your component that will help or you can install the `tns-platform-declaration` module

**Comment by EddyVerbruggen** [comment]
#20 will make this easier.

**Comment by tjvantoll** [comment]
#20 has been merged and pushed out. You can now easily change the “Done” text as well as a few other things. See https://github.com/tjvantoll/nativescript-IQKeyboardManager/blob/54bcec25fe7f09b6d2a4ea8428ac80fb3edb19cd/demo/app/main-view-model.ts#L43 as an example.
