### ISSUE TITLE
Hide IQKeyboard on Click on Button

### ISSUE THREAD

**Issue by pap5508** [tjvantoll/nativescript-IQKeyboardManager#16]
How can I close keypad on click on Send Button... ?

Problem: Currently,to close Keypad 
1. send click and than click Done button to close Keypad

Is that possible way to close keypad on Send button clicked..?

![bildschirmfoto 2017-03-21 um 10 28 23](https://cloud.githubusercontent.com/assets/8488715/24140665/2952d780-0e21-11e7-902b-3f41fd8b7717.png)

**Comment by EddyVerbruggen** [comment]
With #20 merged this will probably work when [this property](https://github.com/EddyVerbruggen/nativescript-IQKeyboardManager/blob/9ebc629c190ae627633912240bd23e669f34ee6f/demo/app/main-view-model.ts#L29) is set.

**Comment by tjvantoll** [comment]
Closing for now as #20 has just been merged and pushed out w/version 1.1.0 of this plugin. @pap5508 if you’re having problems getting the behavior you’re looking for to work let us know.
