### ISSUE TITLE
Keyboard does not appear with the Search bar

### ISSUE THREAD

**Issue by anuragd7** [tjvantoll/nativescript-IQKeyboardManager#17]
Hi the keyboard only seem to work with textview and not with the search bar. so currently dfferent keyboards appear depending on where the user types.  It would be good if the plugin worked with the search bar too.

**Comment by tjvantoll** [comment]
@anuragd7  Sorry for the late response here.

Not sure what we can do about this as this is behavior of the CocoaPod itself. We do now expose the raw plugin typings, so you have a little more power to configure things (see https://github.com/tjvantoll/nativescript-IQKeyboardManager#advanced-usage).

I’m going to close this as I’m not sure what we can really do in this plugin as its just a simple wrapper of the CocoaPod, but if anyone stumbles upon this and has any ideas please comment.
