### ISSUE TITLE
Alternative for Android?

### ISSUE THREAD

**Issue by Yamilquery** [tjvantoll/nativescript-IQKeyboardManager#18]
Is there any alternative to using a similar tool on Android?

**Comment by EddyVerbruggen** [comment]
What's the problem exactly on Android, and what did Google tell you?

**Comment by tjvantoll** [comment]
Closing this as this isn’t an issue with the plugin itself. This would be a good question to ask on the [NativeScript community forum](https://discourse.nativescript.org/).
