### ISSUE TITLE
App Crashes if we are not clicking done or return button

### ISSUE THREAD

**Issue by Jaishankarb** [tjvantoll/nativescript-IQKeyboardManager#21]
The app is crashing when we are moving from one page to next page without tapping the done or return button in the keyboard. It is working fine if we close the keyboard by tapping return or done button.

**Comment by tjvantoll** [comment]
Hey @Jaishankarb,

I’m sorry I missed this. There’s a new version of the plugin out that bumps up the underlying version of IQKeyboardManager. If anyone that sees this is still having this problem with the new version let me know and I can take a look.
