### ISSUE TITLE
Done Button wont display

### ISSUE THREAD

**Issue by jeddWebill** [tjvantoll/nativescript-IQKeyboardManager#25]
Hi so when we build the app on one machine everything is fine but as soon as we build it and run on another machines emulator the Done button disappears. Any ideas?

**Comment by tjvantoll** [comment]
Hey @jeddWebill,

I just published a new 1.2.0 version of the plugin that should address this. Could you give it a shot? If you’re still having the problem let me know here and I can take another look.
