### ISSUE TITLE
Working on simulator but not on real device

### ISSUE THREAD

**Issue by cpvbruno** [tjvantoll/nativescript-IQKeyboardManager#26]
I installed the plugin and it work perfectly into the simulator, but when I deployed to testflight and run in my iPhone, it didnt work.

**Comment by tjvantoll** [comment]
Hey @cpvbruno,

Sorry for the late reply here. I just published a new version of the plugin (1.2) that has some updates for newer versions of iOS. If you’re still having that problem could you give it a shot and see if it addresses your issue?

**Comment by chrissantosproduction** [comment]
I am having the same issue. It works on the simulator, but does not work on my iPhone.

**Comment by cpvbruno** [comment]
I solve the issue by updating the version of the library in my pod file

**Comment by glennsyang** [comment]
this is not working for me on the real device, but it's working in the simulator.
My device is using iOS 11.3.1.  
Nativescript 4.0.0
tns-ios: 4.0.1

version of this plugin : 1.3.0

I noticed that the latest version of the Pod library is 6.0.0, but this plugin installs 5.0.0. Not sure if that has something to do with it.

**Comment by snq** [comment]
Same issue here
