### ISSUE TITLE
Build failed after installing 1.2.0

### ISSUE THREAD

**Issue by halaharr** [tjvantoll/nativescript-IQKeyboardManager#29]
Hi,
    After installing latest version I am not able to build the project. I am getting the following error message.

Thanks

**[!] Unable to satisfy the following requirements:

- `IQKeyboardManager (~> 5.0.0)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `IQKeyboardManager (~> 5.0.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
Command pod failed with exit code 31 Error output:**

**Comment by Nurgunkalol** [comment]
same issue

**Comment by tjvantoll** [comment]
Hey all,

Sorry for the late reply here, and 😞 that you hit problems with the new version. I’m personally unable to recreate this one in new apps, so I have a few questions.

1) What CocoaPod version are you running? (`pod --version`)
2) Have you tried running the app after cleaning out your platform folder? (`rm -rf platforms/ios` and then `tns run ios`)
3) Did you try running `pod repo update` and then run your app again?

Hopefully we can figure out what’s up here.

**Comment by halaharr** [comment]
Hi,
    I am using pod 1.3.1. I did try "tns  remove platform ios" before building. I never tried pod repo update. I will try and let you know. Also for #30 you did mention to update to pod 1.2.0 and I am at 1.3.1. Do I need to downgrade my pod version to 1.2.0?

Thanks

**Comment by halaharr** [comment]
Looks like the latest version of pod is 1.4.0. Do you recommend updating ] to that version?

**Comment by halaharr** [comment]
After doing "pod repo update" with pod 1.3.1 and installing the latest version of nativescript-iqkeyboardmanager I was able to build with success without any warnings and errors.

Thanks for all your help.

**Comment by tjvantoll** [comment]
Awesome! Glad you got it working. And just fyi I’m on CocoaPod version 1.3.1 as well.
