### ISSUE TITLE
Specify a version constraint on the Pod

### ISSUE THREAD

**Issue by maknz** [tjvantoll/nativescript-IQKeyboardManager#3]
At the moment, the bleeding edge version of IQKeyboardManager will be used. This is a bit scary, as even if you specify v1.0.0 strictly of this package, you could still get a new major version of IQKeyboardManager from Cocoapods.

My suggestion would be to specify `~> 4.0.0` in the Podfile so that users will get 4.x up to, but not including 5.x. A future 5.0.0 release is likely to have breaking changes.

**Comment by tjvantoll** [comment]
Hey @maknz. This seems reasonable. Could you send a pull request to add the constraint 😀 ?

**Comment by maknz** [comment]
Of course, apologies for not doing that off the bat :wink:

**Comment by tjvantoll** [comment]
This was handled in 443c1b9b08b2f816f242f1d557df05398a355bf7. Forgot to close this then.
