### ISSUE TITLE
Build warnings with 1.1.0

### ISSUE THREAD

**Issue by halaharr** [tjvantoll/nativescript-IQKeyboardManager#30]
Hi,
   I am getting lot of warnings with 1.1.0.

/Users/halaharvi/Projects/A2Z.FieldCompass/A2Z.FieldCompass/A2Z.FieldCompass/platforms/ios/Pods/IQKeyboardManager/IQKeyboardManager/IQKeyboardReturnKeyHandler.m:305:65: warning: 
      'UITextFieldDidEndEditingReason' is partial: introduced in iOS 10.0 [-Wunguarded-availability]
- (void)textFieldDidEndEditing:(UITextField *)textField reason:(UITextFieldDidEndEditingReason)reason
                                                                ^
In module 'UIKit' imported from /Users/halaharvi/Projects/A2Z.FieldCompass/A2Z.FieldCompass/A2Z.FieldCompass/platforms/ios/Pods/Target Support Files/IQKeyboardManager/IQKeyboardManager-prefix.pch:2:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UITextField.h:48:28: note: 
      'UITextFieldDidEndEditingReason' has been explicitly marked partial here
typedef NS_ENUM(NSInteger, UITextFieldDidEndEditingReason) {
                           ^
/Users/halaharvi/Projects/A2Z.FieldCompass/A2Z.FieldCompass/A2Z.FieldCompass/platforms/ios/Pods/IQKeyboardManager/IQKeyboardManager/IQKeyboardReturnKeyHandler.m:305:1: note: 
      annotate 'textFieldDidEndEditing:reason:' with an availability attribute to silence
- (void)textFieldDidEndEditing:(UITextField *)textField reason:(UITextFieldDidEndEditingReason)reason
^
/Users/halaharvi/Projects/A2Z.FieldCompass/A2Z.FieldCompass/A2Z.FieldCompass/platforms/ios/Pods/IQKeyboardManager/IQKeyboardManager/IQKeyboardReturnKeyHandler.m:499:121: warning: 
      'UITextItemInteraction' is partial: introduced in iOS 10.0 [-Wunguarded-availability]
  ...shouldInteractWithURL:(NSURL *)URL inRange:(NSRange)characterRange interaction:(UITextItemInte...
                                                                                     ^
In module 'UIKit' imported from /Users/halaharvi/Projects/A2Z.FieldCompass/A2Z.FieldCompass/A2Z.FieldCompass/platforms/ios/Pods/Target Support Files/IQKeyboardManager/IQKeyboardManager-prefix.pch:2:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UITextInteraction.h:8:28: note: 
      'UITextItemInteraction' has been explicitly marked partial here
typedef NS_ENUM(NSInteger, UITextItemInteraction) {
                           ^
/Users/halaharvi/Projects/A2Z.FieldCompass/A2Z.FieldCompass/A2Z.FieldCompass/platforms/ios/Pods/IQKeyboardManager/IQKeyboardManager/IQKeyboardReturnKeyHandler.m:499:1: note: 
      annotate 'textView:shouldInteractWithURL:inRange:interaction:' with an availability attribute to
      silence
- (BOOL)textView:(UITextView *)textView shouldInteractWithURL:(NSURL *)URL inRange:(NSRange)ch...
^
/Users/halaharvi/Projects/A2Z.FieldCompass/A2Z.FieldCompass/A2Z.FieldCompass/platforms/ios/Pods/IQKeyboardManager/IQKeyboardManager/IQKeyboardReturnKeyHandler.m:515:154: warning: 
      'UITextItemInteraction' is partial: introduced in iOS 10.0 [-Wunguarded-availability]
  ...*)textAttachment inRange:(NSRange)characterRange interaction:(UITextItemInteraction)interaction
                                                                   ^
In module 'UIKit' imported from /Users/halaharvi/Projects/A2Z.FieldCompass/A2Z.FieldCompass/A2Z.FieldCompass/platforms/ios/Pods/Target Support Files/IQKeyboardManager/IQKeyboardManager-prefix.pch:2:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UITextInteraction.h:8:28: note: 
      'UITextItemInteraction' has been explicitly marked partial here
typedef NS_ENUM(NSInteger, UITextItemInteraction) {
                           ^
/Users/halaharvi/Projects/A2Z.FieldCompass/A2Z.FieldCompass/A2Z.FieldCompass/platforms/ios/Pods/IQKeyboardManager/IQKeyboardManager/IQKeyboardReturnKeyHandler.m:515:1: note: 
      annotate 'textView:shouldInteractWithTextAttachment:inRange:interaction:' with an availability
      attribute to silence
- (BOOL)textView:(UITextView *)textView shouldInteractWithTextAttachment:(NSTextAttachment *)t...
^
/Users/halaharvi/Projects/A2Z.FieldCompass/A2Z.FieldCompass/A2Z.FieldCompass/platforms/ios/Pods/IQKeyboardManager/IQKeyboardManager/IQKeyboardReturnKeyHandler.m:316:19: warning: 
      'textFieldDidEndEditing:reason:' is only available on iOS 10.0 or newer
      [-Wunguarded-availability]
        [delegate textFieldDidEndEditing:textField reason:reason];
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In module 'UIKit' imported from /Users/halaharvi/Projects/A2Z.FieldCompass/A2Z.FieldCompass/A2Z.FieldCompass/platforms/ios/Pods/Target Support Files/IQKeyboardManager/IQKeyboardManager-prefix.pch:2:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UITextField.h:134:1: note: 
      'textFieldDidEndEditing:reason:' has been explicitly marked partial here
- (void)textFieldDidEndEditing:(UITextField *)textField reason:(UITextFieldDidEndEditingReason...
^
/Users/halaharvi/Projects/A2Z.FieldCompass/A2Z.FieldCompass/A2Z.FieldCompass/platforms/ios/Pods/IQKeyboardManager/IQKeyboardManager/IQKeyboardReturnKeyHandler.m:316:19: note: 
      enclose 'textFieldDidEndEditing:reason:' in an @available check to silence this warning
        [delegate textFieldDidEndEditing:textField reason:reason];
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/halaharvi/Projects/A2Z.FieldCompass/A2Z.FieldCompass/A2Z.FieldCompass/platforms/ios/Pods/IQKeyboardManager/IQKeyboardManager/IQKeyboardReturnKeyHandler.m:510:26: warning: 
      'textView:shouldInteractWithURL:inRange:interaction:' is only available on iOS 10.0 or newer
      [-Wunguarded-availability]
  ...textView:textView shouldInteractWithURL:URL inRange:characterRange interaction:interaction];
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In module 'UIKit' imported from /Users/halaharvi/Projects/A2Z.FieldCompass/A2Z.FieldCompass/A2Z.FieldCompass/platforms/ios/Pods/Target Support Files/IQKeyboardManager/IQKeyboardManager-prefix.pch:2:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UITextView.h:40:1: note: 
      'textView:shouldInteractWithURL:inRange:interaction:' has been explicitly marked partial here
- (BOOL)textView:(UITextView *)textView shouldInteractWithURL:(NSURL *)URL inRange:(NSRange)ch...
^
/Users/halaharvi/Projects/A2Z.FieldCompass/A2Z.FieldCompass/A2Z.FieldCompass/platforms/ios/Pods/IQKeyboardManager/IQKeyboardManager/IQKeyboardReturnKeyHandler.m:510:26: note: 
      enclose 'textView:shouldInteractWithURL:inRange:interaction:' in an @available check to silence
      this warning
  ...textView:textView shouldInteractWithURL:URL inRange:characterRange interaction:interaction];
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/halaharvi/Projects/A2Z.FieldCompass/A2Z.FieldCompass/A2Z.FieldCompass/platforms/ios/Pods/IQKeyboardManager/IQKeyboardManager/IQKeyboardReturnKeyHandler.m:526:26: warning: 
      'textView:shouldInteractWithTextAttachment:inRange:interaction:' is only available on iOS 10.0
      or newer [-Wunguarded-availability]
  ...textView:textView shouldInteractWithTextAttachment:textAttachment inRange:characterRange interaction:interaction];
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In module 'UIKit' imported from /Users/halaharvi/Projects/A2Z.FieldCompass/A2Z.FieldCompass/A2Z.FieldCompass/platforms/ios/Pods/Target Support Files/IQKeyboardManager/IQKeyboardManager-prefix.pch:2:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UITextView.h:41:1: note: 
      'textView:shouldInteractWithTextAttachment:inRange:interaction:' has been explicitly marked
      partial here
- (BOOL)textView:(UITextView *)textView shouldInteractWithTextAttachment:(NSTextAttachment *)t...
^
/Users/halaharvi/Projects/A2Z.FieldCompass/A2Z.FieldCompass/A2Z.FieldCompass/platforms/ios/Pods/IQKeyboardManager/IQKeyboardManager/IQKeyboardReturnKeyHandler.m:526:26: note: 
      enclose 'textView:shouldInteractWithTextAttachment:inRange:interaction:' in an @available check
      to silence this warning
  ...textView:textView shouldInteractWithTextAttachment:textAttachment inRange:characterRange interaction:interaction];
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
6 warnings generated.
=== BUILD TARGET IQKeyboardManager OF PROJECT Pods WITH CONFIGURATION Debug ===
/Users/halaharvi/Projects/A2Z.FieldCompass/A2Z.FieldCompass/A2Z.FieldCompass/platforms/ios/Pods/IQKeyboardManager/IQKeyboardManager/IQToolbar/IQUIView+IQKeyboardToolbar.m:572:42: warning: 
      'imageFlippedForRightToLeftLayoutDirection' is only available on iOS 9.0 or newer
      [-Wunguarded-availability]
        imageLeftArrow = [imageLeftArrow imageFlippedForRightToLeftLayoutDirection];
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In module 'UIKit' imported from /Users/halaharvi/Projects/A2Z.FieldCompass/A2Z.FieldCompass/A2Z.FieldCompass/platforms/ios/Pods/Target Support Files/IQKeyboardManager/IQKeyboardManager-prefix.pch:2:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIImage.h:143:1: note: 
      'imageFlippedForRightToLeftLayoutDirection' has been explicitly marked partial here
- (UIImage *)imageFlippedForRightToLeftLayoutDirection NS_AVAILABLE_IOS(9_0);
^
/Users/halaharvi/Projects/A2Z.FieldCompass/A2Z.FieldCompass/A2Z.FieldCompass/platforms/ios/Pods/IQKeyboardManager/IQKeyboardManager/IQToolbar/IQUIView+IQKeyboardToolbar.m:572:42: note: 
      enclose 'imageFlippedForRightToLeftLayoutDirection' in an @available check to silence this
      warning
        imageLeftArrow = [imageLeftArrow imageFlippedForRightToLeftLayoutDirection];
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/halaharvi/Projects/A2Z.FieldCompass/A2Z.FieldCompass/A2Z.FieldCompass/platforms/ios/Pods/IQKeyboardManager/IQKeyboardManager/IQToolbar/IQUIView+IQKeyboardToolbar.m:573:44: warning: 
      'imageFlippedForRightToLeftLayoutDirection' is only available on iOS 9.0 or newer
      [-Wunguarded-availability]
        imageRightArrow = [imageRightArrow imageFlippedForRightToLeftLayoutDirection];
                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In module 'UIKit' imported from /Users/halaharvi/Projects/A2Z.FieldCompass/A2Z.FieldCompass/A2Z.FieldCompass/platforms/ios/Pods/Target Support Files/IQKeyboardManager/IQKeyboardManager-prefix.pch:2:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIImage.h:143:1: note: 
      'imageFlippedForRightToLeftLayoutDirection' has been explicitly marked partial here
- (UIImage *)imageFlippedForRightToLeftLayoutDirection NS_AVAILABLE_IOS(9_0);
^
/Users/halaharvi/Projects/A2Z.FieldCompass/A2Z.FieldCompass/A2Z.FieldCompass/platforms/ios/Pods/IQKeyboardManager/IQKeyboardManager/IQToolbar/IQUIView+IQKeyboardToolbar.m:573:44: note: 
      enclose 'imageFlippedForRightToLeftLayoutDirection' in an @available check to silence this
      warning
        imageRightArrow = [imageRightArrow imageFlippedForRightToLeftLayoutDirection];
                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/halaharvi/Projects/A2Z.FieldCompass/A2Z.FieldCompass/A2Z.FieldCompass/platforms/ios/Pods/IQKeyboardManager/IQKeyboardManager/IQToolbar/IQUIView+IQKeyboardToolbar.m:714:42: warning: 
      'imageFlippedForRightToLeftLayoutDirection' is only available on iOS 9.0 or newer
      [-Wunguarded-availability]
        imageLeftArrow = [imageLeftArrow imageFlippedForRightToLeftLayoutDirection];
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In module 'UIKit' imported from /Users/halaharvi/Projects/A2Z.FieldCompass/A2Z.FieldCompass/A2Z.FieldCompass/platforms/ios/Pods/Target Support Files/IQKeyboardManager/IQKeyboardManager-prefix.pch:2:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIImage.h:143:1: note: 
      'imageFlippedForRightToLeftLayoutDirection' has been explicitly marked partial here
- (UIImage *)imageFlippedForRightToLeftLayoutDirection NS_AVAILABLE_IOS(9_0);
^
/Users/halaharvi/Projects/A2Z.FieldCompass/A2Z.FieldCompass/A2Z.FieldCompass/platforms/ios/Pods/IQKeyboardManager/IQKeyboardManager/IQToolbar/IQUIView+IQKeyboardToolbar.m:714:42: note: 
      enclose 'imageFlippedForRightToLeftLayoutDirection' in an @available check to silence this
      warning
        imageLeftArrow = [imageLeftArrow imageFlippedForRightToLeftLayoutDirection];
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/halaharvi/Projects/A2Z.FieldCompass/A2Z.FieldCompass/A2Z.FieldCompass/platforms/ios/Pods/IQKeyboardManager/IQKeyboardManager/IQToolbar/IQUIView+IQKeyboardToolbar.m:715:44: warning: 
      'imageFlippedForRightToLeftLayoutDirection' is only available on iOS 9.0 or newer
      [-Wunguarded-availability]
        imageRightArrow = [imageRightArrow imageFlippedForRightToLeftLayoutDirection];
                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In module 'UIKit' imported from /Users/halaharvi/Projects/A2Z.FieldCompass/A2Z.FieldCompass/A2Z.FieldCompass/platforms/ios/Pods/Target Support Files/IQKeyboardManager/IQKeyboardManager-prefix.pch:2:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIImage.h:143:1: note: 
      'imageFlippedForRightToLeftLayoutDirection' has been explicitly marked partial here
- (UIImage *)imageFlippedForRightToLeftLayoutDirection NS_AVAILABLE_IOS(9_0);
^
/Users/halaharvi/Projects/A2Z.FieldCompass/A2Z.FieldCompass/A2Z.FieldCompass/platforms/ios/Pods/IQKeyboardManager/IQKeyboardManager/IQToolbar/IQUIView+IQKeyboardToolbar.m:715:44: note: 
      enclose 'imageFlippedForRightToLeftLayoutDirection' in an @available check to silence this
      warning
        imageRightArrow = [imageRightArrow imageFlippedForRightToLeftLayoutDirection];
                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/halaharvi/Projects/A2Z.FieldCompass/A2Z.FieldCompass/A2Z.FieldCompass/platforms/ios/Pods/IQKeyboardManager/IQKeyboardManager/IQToolbar/IQUIView+IQKeyboardToolbar.m:858:42: warning: 
      'imageFlippedForRightToLeftLayoutDirection' is only available on iOS 9.0 or newer
      [-Wunguarded-availability]
        imageLeftArrow = [imageLeftArrow imageFlippedForRightToLeftLayoutDirection];
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In module 'UIKit' imported from /Users/halaharvi/Projects/A2Z.FieldCompass/A2Z.FieldCompass/A2Z.FieldCompass/platforms/ios/Pods/Target Support Files/IQKeyboardManager/IQKeyboardManager-prefix.pch:2:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIImage.h:143:1: note: 
      'imageFlippedForRightToLeftLayoutDirection' has been explicitly marked partial here
- (UIImage *)imageFlippedForRightToLeftLayoutDirection NS_AVAILABLE_IOS(9_0);
^
/Users/halaharvi/Projects/A2Z.FieldCompass/A2Z.FieldCompass/A2Z.FieldCompass/platforms/ios/Pods/IQKeyboardManager/IQKeyboardManager/IQToolbar/IQUIView+IQKeyboardToolbar.m:858:42: note: 
      enclose 'imageFlippedForRightToLeftLayoutDirection' in an @available check to silence this
      warning
        imageLeftArrow = [imageLeftArrow imageFlippedForRightToLeftLayoutDirection];
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/halaharvi/Projects/A2Z.FieldCompass/A2Z.FieldCompass/A2Z.FieldCompass/platforms/ios/Pods/IQKeyboardManager/IQKeyboardManager/IQToolbar/IQUIView+IQKeyboardToolbar.m:859:44: warning: 
      'imageFlippedForRightToLeftLayoutDirection' is only available on iOS 9.0 or newer
      [-Wunguarded-availability]
        imageRightArrow = [imageRightArrow imageFlippedForRightToLeftLayoutDirection];
                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In module 'UIKit' imported from /Users/halaharvi/Projects/A2Z.FieldCompass/A2Z.FieldCompass/A2Z.FieldCompass/platforms/ios/Pods/Target Support Files/IQKeyboardManager/IQKeyboardManager-prefix.pch:2:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIImage.h:143:1: note: 
      'imageFlippedForRightToLeftLayoutDirection' has been explicitly marked partial here
- (UIImage *)imageFlippedForRightToLeftLayoutDirection NS_AVAILABLE_IOS(9_0);
^
/Users/halaharvi/Projects/A2Z.FieldCompass/A2Z.FieldCompass/A2Z.FieldCompass/platforms/ios/Pods/IQKeyboardManager/IQKeyboardManager/IQToolbar/IQUIView+IQKeyboardToolbar.m:859:44: note: 
      enclose 'imageFlippedForRightToLeftLayoutDirection' in an @available check to silence this
      warning
        imageRightArrow = [imageRightArrow imageFlippedForRightToLeftLayoutDirection];
                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
6 warnings generated.
/Users/halaharvi/Projects/A2Z.FieldCompass/A2Z.FieldCompass/A2Z.FieldCompass/platforms/ios/Pods/IQKeyboardManager/IQKeyboardManager/IQKeyboardReturnKeyHandler.m:305:65: warning: 
      'UITextFieldDidEndEditingReason' is partial: introduced in iOS 10.0 [-Wunguarded-availability]
- (void)textFieldDidEndEditing:(UITextField *)textField reason:(UITextFieldDidEndEditingReason)reason
                                                                ^
In module 'UIKit' imported from /Users/halaharvi/Projects/A2Z.FieldCompass/A2Z.FieldCompass/A2Z.FieldCompass/platforms/ios/Pods/Target Support Files/IQKeyboardManager/IQKeyboardManager-prefix.pch:2:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UITextField.h:48:28: note: 
      'UITextFieldDidEndEditingReason' has been explicitly marked partial here
typedef NS_ENUM(NSInteger, UITextFieldDidEndEditingReason) {
                           ^
/Users/halaharvi/Projects/A2Z.FieldCompass/A2Z.FieldCompass/A2Z.FieldCompass/platforms/ios/Pods/IQKeyboardManager/IQKeyboardManager/IQKeyboardReturnKeyHandler.m:305:1: note: 
      annotate 'textFieldDidEndEditing:reason:' with an availability attribute to silence
- (void)textFieldDidEndEditing:(UITextField *)textField reason:(UITextFieldDidEndEditingReason)reason
^
/Users/halaharvi/Projects/A2Z.FieldCompass/A2Z.FieldCompass/A2Z.FieldCompass/platforms/ios/Pods/IQKeyboardManager/IQKeyboardManager/IQKeyboardReturnKeyHandler.m:499:121: warning: 
      'UITextItemInteraction' is partial: introduced in iOS 10.0 [-Wunguarded-availability]
  ...shouldInteractWithURL:(NSURL *)URL inRange:(NSRange)characterRange interaction:(UITextItemInte...
                                                                                     ^
In module 'UIKit' imported from /Users/halaharvi/Projects/A2Z.FieldCompass/A2Z.FieldCompass/A2Z.FieldCompass/platforms/ios/Pods/Target Support Files/IQKeyboardManager/IQKeyboardManager-prefix.pch:2:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UITextInteraction.h:8:28: note: 
      'UITextItemInteraction' has been explicitly marked partial here
typedef NS_ENUM(NSInteger, UITextItemInteraction) {
                           ^
/Users/halaharvi/Projects/A2Z.FieldCompass/A2Z.FieldCompass/A2Z.FieldCompass/platforms/ios/Pods/IQKeyboardManager/IQKeyboardManager/IQKeyboardReturnKeyHandler.m:499:1: note: 
      annotate 'textView:shouldInteractWithURL:inRange:interaction:' with an availability attribute to
      silence
- (BOOL)textView:(UITextView *)textView shouldInteractWithURL:(NSURL *)URL inRange:(NSRange)ch...
^
/Users/halaharvi/Projects/A2Z.FieldCompass/A2Z.FieldCompass/A2Z.FieldCompass/platforms/ios/Pods/IQKeyboardManager/IQKeyboardManager/IQKeyboardReturnKeyHandler.m:515:154: warning: 
      'UITextItemInteraction' is partial: introduced in iOS 10.0 [-Wunguarded-availability]
  ...*)textAttachment inRange:(NSRange)characterRange interaction:(UITextItemInteraction)interaction
                                                                   ^
In module 'UIKit' imported from /Users/halaharvi/Projects/A2Z.FieldCompass/A2Z.FieldCompass/A2Z.FieldCompass/platforms/ios/Pods/Target Support Files/IQKeyboardManager/IQKeyboardManager-prefix.pch:2:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UITextInteraction.h:8:28: note: 
      'UITextItemInteraction' has been explicitly marked partial here
typedef NS_ENUM(NSInteger, UITextItemInteraction) {
                           ^
/Users/halaharvi/Projects/A2Z.FieldCompass/A2Z.FieldCompass/A2Z.FieldCompass/platforms/ios/Pods/IQKeyboardManager/IQKeyboardManager/IQKeyboardReturnKeyHandler.m:515:1: note: 
      annotate 'textView:shouldInteractWithTextAttachment:inRange:interaction:' with an availability
      attribute to silence
- (BOOL)textView:(UITextView *)textView shouldInteractWithTextAttachment:(NSTextAttachment *)t...
^
/Users/halaharvi/Projects/A2Z.FieldCompass/A2Z.FieldCompass/A2Z.FieldCompass/platforms/ios/Pods/IQKeyboardManager/IQKeyboardManager/IQKeyboardReturnKeyHandler.m:316:19: warning: 
      'textFieldDidEndEditing:reason:' is only available on iOS 10.0 or newer
      [-Wunguarded-availability]
        [delegate textFieldDidEndEditing:textField reason:reason];
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In module 'UIKit' imported from /Users/halaharvi/Projects/A2Z.FieldCompass/A2Z.FieldCompass/A2Z.FieldCompass/platforms/ios/Pods/Target Support Files/IQKeyboardManager/IQKeyboardManager-prefix.pch:2:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UITextField.h:134:1: note: 
      'textFieldDidEndEditing:reason:' has been explicitly marked partial here
- (void)textFieldDidEndEditing:(UITextField *)textField reason:(UITextFieldDidEndEditingReason...
^
/Users/halaharvi/Projects/A2Z.FieldCompass/A2Z.FieldCompass/A2Z.FieldCompass/platforms/ios/Pods/IQKeyboardManager/IQKeyboardManager/IQKeyboardReturnKeyHandler.m:316:19: note: 
      enclose 'textFieldDidEndEditing:reason:' in an @available check to silence this warning
        [delegate textFieldDidEndEditing:textField reason:reason];
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/halaharvi/Projects/A2Z.FieldCompass/A2Z.FieldCompass/A2Z.FieldCompass/platforms/ios/Pods/IQKeyboardManager/IQKeyboardManager/IQKeyboardReturnKeyHandler.m:510:26: warning: 
      'textView:shouldInteractWithURL:inRange:interaction:' is only available on iOS 10.0 or newer
      [-Wunguarded-availability]
  ...textView:textView shouldInteractWithURL:URL inRange:characterRange interaction:interaction];
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In module 'UIKit' imported from /Users/halaharvi/Projects/A2Z.FieldCompass/A2Z.FieldCompass/A2Z.FieldCompass/platforms/ios/Pods/Target Support Files/IQKeyboardManager/IQKeyboardManager-prefix.pch:2:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UITextView.h:40:1: note: 
      'textView:shouldInteractWithURL:inRange:interaction:' has been explicitly marked partial here
- (BOOL)textView:(UITextView *)textView shouldInteractWithURL:(NSURL *)URL inRange:(NSRange)ch...
^
/Users/halaharvi/Projects/A2Z.FieldCompass/A2Z.FieldCompass/A2Z.FieldCompass/platforms/ios/Pods/IQKeyboardManager/IQKeyboardManager/IQKeyboardReturnKeyHandler.m:510:26: note: 
      enclose 'textView:shouldInteractWithURL:inRange:interaction:' in an @available check to silence
      this warning
  ...textView:textView shouldInteractWithURL:URL inRange:characterRange interaction:interaction];
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/halaharvi/Projects/A2Z.FieldCompass/A2Z.FieldCompass/A2Z.FieldCompass/platforms/ios/Pods/IQKeyboardManager/IQKeyboardManager/IQKeyboardReturnKeyHandler.m:526:26: warning: 
      'textView:shouldInteractWithTextAttachment:inRange:interaction:' is only available on iOS 10.0
      or newer [-Wunguarded-availability]
  ...textView:textView shouldInteractWithTextAttachment:textAttachment inRange:characterRange interaction:interaction];
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In module 'UIKit' imported from /Users/halaharvi/Projects/A2Z.FieldCompass/A2Z.FieldCompass/A2Z.FieldCompass/platforms/ios/Pods/Target Support Files/IQKeyboardManager/IQKeyboardManager-prefix.pch:2:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UITextView.h:41:1: note: 
      'textView:shouldInteractWithTextAttachment:inRange:interaction:' has been explicitly marked
      partial here
- (BOOL)textView:(UITextView *)textView shouldInteractWithTextAttachment:(NSTextAttachment *)t...
^
/Users/halaharvi/Projects/A2Z.FieldCompass/A2Z.FieldCompass/A2Z.FieldCompass/platforms/ios/Pods/IQKeyboardManager/IQKeyboardManager/IQKeyboardReturnKeyHandler.m:526:26: note: 
      enclose 'textView:shouldInteractWithTextAttachment:inRange:interaction:' in an @available check
      to silence this warning
  ...textView:textView shouldInteractWithTextAttachment:textAttachment inRange:characterRange interaction:interaction];
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
6 warnings generated.
=== BUILD TARGET IQKeyboardManager OF PROJECT Pods WITH CONFIGURATION Debug ===
/Users/halaharvi/Projects/A2Z.FieldCompass/A2Z.FieldCompass/A2Z.FieldCompass/platforms/ios/Pods/IQKeyboardManager/IQKeyboardManager/IQToolbar/IQUIView+IQKeyboardToolbar.m:572:42: warning: 
      'imageFlippedForRightToLeftLayoutDirection' is only available on iOS 9.0 or newer
      [-Wunguarded-availability]
        imageLeftArrow = [imageLeftArrow imageFlippedForRightToLeftLayoutDirection];
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In module 'UIKit' imported from /Users/halaharvi/Projects/A2Z.FieldCompass/A2Z.FieldCompass/A2Z.FieldCompass/platforms/ios/Pods/Target Support Files/IQKeyboardManager/IQKeyboardManager-prefix.pch:2:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIImage.h:143:1: note: 
      'imageFlippedForRightToLeftLayoutDirection

**Comment by tjvantoll** [comment]
Hey @halaharr,

Thanks for reporting these and sorry for the late replies. These warnings are the reason we needed to upgrade the underlying pod, so 1.2.0 should fix these problems (if not let me know). I’m going to see what’s up with #29 so that hopefully you can upgrade.
