### ISSUE TITLE
Incompatibility with tns-ios 4.0.1

### ISSUE THREAD

**Issue by arcovoltaico** [tjvantoll/nativescript-IQKeyboardManager#33]
Hi,
I have been happily using your nice dependency, but after upgrading from tns-ios 3.4.1 to 4.0.1 when I tap a textfield the screen go up ok, but when I press a key then, after the update, the screen go up about  20px more ...  so on an iPhone SE when the keyboard disappears then the screen goes down keeping 20px hidden by my action bar. If it matters, I'm using Angular TypeScript {N}. Thx !!

**Comment by armackey** [comment]
Same here.

**Comment by darxmac** [comment]
same

**Comment by gsmedley** [comment]
Are you using a ScrollView? I found I had to wrap all my ScrollViews in StackLayouts after the 4.0.1 upgrade.

**Comment by arcovoltaico** [comment]
@gsmedley Thanks, but unfortunately all of them were already wrapped with StackLayouts .... so still experiencing the problem :-(

**Comment by hosikiti** [comment]
Same. Seems scrollview at top level of component should be wrapped by stacklayout (or other container, not sure)

Not worked:
```
<ScrollView>
</ScrollView>
```
Worked:
```
<StackLayout>
  <ScrollView>
  </ScrollView>
</StackLayout>
```

**Comment by arcovoltaico** [comment]
Finally working with the workaround and with some dependencies updates

**Comment by AquilesOliveira** [comment]
The solution is to simply use the `<PreviousNextView>` tags between the forms components and it will work perfectly
