### ISSUE TITLE
Working on simulator but not real device

### ISSUE THREAD

**Issue by glennsyang** [tjvantoll/nativescript-IQKeyboardManager#35]
Similar issue to https://github.com/tjvantoll/nativescript-IQKeyboardManager/issues/26

I installed the plugin and it work perfectly into the simulator, but when I deployed to testflight and run on my iPhone, it didnt work.

My device (iPhone6s) is using iOS 11.3.1.
Nativescript 4.0.0
tns-ios: 4.0.1

version of this plugin : 1.3.0

I noticed that the latest version of the Pod library is 6.0.0, but this plugin installs 5.0.0. Not sure if that has something to do with it...

**Comment by kerby82** [comment]
Same problem with:
Nativescript 4.0.0
tns-ios: 4.0.1
"nativescript-iqkeyboardmanager": "^1.3.0"

**Comment by glennsyang** [comment]
I cloned a local repo of this plugin, in the src/platforms/ios/Podfile i changed the entry to:

pod 'IQKeyboardManager', '6.0.0'

removed the plugin from my project, added the local version i just modified, and  tns build ios.

And it worked on my iOS 11.3.1 phone!
if you need any help, let me know.

**Comment by kerby82** [comment]
Thanks for the workaround.

But this solution for production apps is a bit scary since it has a lot of drawbacks and dangers

**Comment by EddyVerbruggen** [comment]
See #52.
