### ISSUE TITLE
Is TextView supported ?

### ISSUE THREAD

**Issue by b02505048** [tjvantoll/nativescript-IQKeyboardManager#44]
I have a `<TextView editable="true" />` and when I'm typing with IQKeyboardManager, it won't scroll to the newest line automatically when I pressed `return`, the newest line will always be covered by keyboard.

Any solution for this? Thank you.

**Comment by EddyVerbruggen** [comment]
Perhaps you can work around it by increasing the distance between the cursor and the keyboard? 

https://github.com/tjvantoll/nativescript-IQKeyboardManager/blob/1b5ef97cf016dd2792b83473445c2193740e6fd9/demo/app/main-view-model.ts#L51
