### ISSUE TITLE
How to get Toolbar to appear with SearchBar component?

### ISSUE THREAD

**Issue by acrollet** [tjvantoll/nativescript-IQKeyboardManager#49]
I'm using IQKeyboardManager with Vue and it's working nicely for a Textfield. I'm not able to get the toolbar to appear when typing in a SearchBar component, any hints? Thanks for the plugin!

**Comment by EddyVerbruggen** [comment]
Unfortunately, this seems to be intentional. Check this issue and the comments by the author of IQKeyboardManager: https://github.com/hackiftekhar/IQKeyboardManager/issues/680
