### ISSUE TITLE
Add option to hide the Done button

### ISSUE THREAD

**Issue by Daxito** [tjvantoll/nativescript-IQKeyboardManager#5]
It would be nice if we could hide the Done button located at the top of the keyboard, after all, all we want is to make sure the keyboard does not cover the text field.

**Comment by tjvantoll** [comment]
Hey @Daxito,

You should be able to do that with the following code:

``` XML
<Page loaded="loaded">
  <TextField id="foo" />
</Page>
```

``` JavaScript
exports.loaded = function(args) {
  var page = args.object;
  page.getViewById("foo").ios.inputAccessoryView = UIView.alloc().init();
};
```

If that doesn’t work for you let me know.

**Comment by Daxito** [comment]
Yes it worked!!! Thank you so much!

**Comment by Yamilquery** [comment]
No funciona con Angular 2.

`error TS2304: Cannot find name 'UIView'.`

:(

**Comment by mn-martin** [comment]
Quick tip for anyones looking here: If you just want to change the button text you could do something like that in your app.ts file:

```
declare const IQKeyboardManager: any;
IQKeyboardManager.sharedManager().toolbarDoneBarButtonItemText = "Fertig";
```

**Comment by Yamilquery** [comment]
@mn-martin Thank you so much! It worked! 👍

**Comment by kambl4** [comment]
How can I do it in nativescript-vue?

**Comment by dicren** [comment]
> How can I do it in nativescript-vue?

If you want remove all the bar 

```javascript
const keyBoardManager = IQKeyboardManager.sharedManager();
keyBoardManager.enableAutoToolbar = false;
```

If you want to change the button text

```javascript
const keyBoardManager = IQKeyboardManager.sharedManager();
keyBoardManager.toolbarDoneBarButtonItemText = "all right!";
```

Not need import anything

**Comment by BMwanza** [comment]
Thanks @DiCrEn worked for me, using NS Vanilla 🍦
