### ISSUE TITLE
Cannot install the plugin 

### ISSUE THREAD

**Issue by xavierburzig** [tjvantoll/nativescript-IQKeyboardManager#53]
Hi everybody, 

I'm actually trying to install the plugin but I got a 503 error appearing. I tried to install another plugin and the error comes up only with this plugin, I also tried with this line and I got the same 
tns plugin add nativescript-iqkeyboardmanager
Here is a screenshot of what I got :

![image](https://user-images.githubusercontent.com/25203328/53334545-72782780-38f9-11e9-94be-a4ffd03b7c31.png)

In advance, Cheers 

Xavier

**Comment by EddyVerbruggen** [comment]
Can you try: tns plugin add nativescript-iq..etc?

**Comment by xavierburzig** [comment]
Hi @EddyVerbruggen,

Here is what I got, I tried with another laptop and also another internet connection.

![thumbnail_capture](https://user-images.githubusercontent.com/25203328/53410334-d0714180-39c3-11e9-8fcf-1d55af8e4cfc.jpg)
 
Xavier

**Comment by EddyVerbruggen** [comment]
@xavierburzig Are you behind a proxy? Search the web for `npm 503` and you'll see tons of similar issues.

**Comment by xavierburzig** [comment]
Hi @EddyVerbruggen, 

I think I figured it out, it's look like it's because of the version of nativescript I'm using and the different dependencies could you tell me what's the minimum version to use this plugin. 
Then I will mark this issue as resolved, again cheers for your time.

Xavier

**Comment by EddyVerbruggen** [comment]
https://github.com/tjvantoll/nativescript-IQKeyboardManager/blob/1b5ef97cf016dd2792b83473445c2193740e6fd9/src/package.json#L9-L10
