### ISSUE TITLE
Hint in textView toolbar

### ISSUE THREAD

**Issue by BigWillie** [tjvantoll/nativescript-IQKeyboardManager#57]
is it possible to show the 'hint' in a textView toolbar?

**Comment by EddyVerbruggen** [comment]
You mean like those 'Email address' and 'Password' fields in this animated gif? https://github.com/tjvantoll/nativescript-IQKeyboardManager#nativescript-iqkeyboardmanager-plugin .. I think that's the default behavior if a hint was added, no?

**Comment by BigWillie** [comment]
Wow! thanks for the quick reply :) Yes - exactly like those... it doesn't seem to work with TextView fields, but does work with TextField..

I would use TextField if it were multiline. Killer keyboard by the way - has solved so many problems for m :) thanks!

**Comment by BigWillie** [comment]
eg:

`<TextView hint="Additional Information" v-model="additional_information" />`

Does not show hint, but 

`<TextField  hint="Additional Information" v-model="additional_information" />`

does show the hint

**Comment by EddyVerbruggen** [comment]
Ah, hmm, good catch. Not sure I've ever tried that actually. But hang on, I have an idea.

**Comment by BigWillie** [comment]
Cool :) Thanks!

**Comment by EddyVerbruggen** [comment]
If you install version 1.5.0 now, you can use [`TextViewWithHint` like this](https://github.com/tjvantoll/nativescript-IQKeyboardManager/blob/9b786eb5d6912fb4d848615faae1fd5caef3560e/demo/app/main-page.xml#L42).

The reason you need a special TextView patched by the plugin is because the internal library (IQKeyboardManager) uses its own extension of iOS' `UITextView` called `IQTextView` which the plugin now also extends when `TextViewWithHint` is used. This adds support for a `placeholder` property which I've wired to NativeScript's `hint` property.

**Comment by BigWillie** [comment]
Amazing! thank you!!! 👍

**Comment by BigWillie** [comment]
@EddyVerbruggen sorry for the delay, only just got around to testing it as was having a mare of a time with webpack... in the end I just copied my files out into a new native script project...

I put the tag into my vue nativescript app - and any component which contains it fails to load. Unfortunately, the logs don't tell me why...

  <StackLayout class="input-field" marginBottom="20">
          <ScrollView class="textArea" height="200" row="0">
            <IQKeyboardManager:TextViewWithHint hint="Additional Information" v-model="additional_information" ref="additional_information"   />
          </ScrollView>
        </StackLayout>

**Comment by EddyVerbruggen** [comment]
Did you register the tag? I didn’t have time to document that, but it’s extremely similar to https://github.com/EddyVerbruggen/nativescript-IQKeyboardManager#nativescript-w-vue-usage

**Comment by BigWillie** [comment]
Thanks. Yep - I added

`Vue.registerElement("TextViewWithHint", () => require("nativescript-iqkeyboardmanager").TextViewWithHint)`

to my app.js (main.js) file - and it isn't working for me?

**Comment by EddyVerbruggen** [comment]
Ha, yeah, that `IQKeyboardManager:` prefix is only for plain-{N} apps, not for Angular and Vue. Glad you figured that out! Will change the readme a little. 👍
