### ISSUE TITLE
Doesn't seem to build properly in TNS 2.0

### ISSUE THREAD

**Issue by NathanaelA** [tjvantoll/nativescript-IQKeyboardManager#6]
Trying to build this with --release --for-device on 2.0 produces this error:

Ld /Users/mac/Library/Developer/Xcode/DerivedData/test2-gghjzraszsaqbzbqxpuhzgopotmi/Build/Intermediates/test2.build/Release-iphoneos/test2.build/Objects-normal/arm64/test2 normal arm64
    cd /Users/mac/Source/test2/platforms/ios
    export IPHONEOS_DEPLOYMENT_TARGET=8.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk -L/Users/mac/Source/test2/platforms/ios/build/device -F/Users/mac/Source/test2/platforms/ios/build/device -F/Users/mac/Source/test2/platforms/ios/../../lib/iOS -F../../lib/iOS -filelist /Users/mac/Library/Developer/Xcode/DerivedData/test2-gghjzraszsaqbzbqxpuhzgopotmi/Build/Intermediates/test2.build/Release-iphoneos/test2.build/Objects-normal/arm64/test2.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -rpath -Xlinker @executable_path/Frameworks -miphoneos-version-min=8.0 -dead_strip /Users/mac/Source/test2/platforms/ios/../../node_modules/nativescript-app-protection/hooks/ios/k -ObjC -sectcreate __DATA __bin_data -framework IQKeyboardManager -ObjC -sectcreate __DATA __TNSMetadata /Users/mac/Source/test2/platforms/ios/build/device/metadata-arm64.bin -lNativeScript -L/Users/mac/Source/test2/platforms/ios/internal/NativeScript/lib -licucore -lz -lc++ -framework Foundation -framework UIKit -framework CoreGraphics -framework MobileCoreServices -framework Security -fobjc-arc -fobjc-link-runtime /Users/mac/Source/test2/lib/iOS/AppProtection.a -framework TelerikUI -framework Pods_test2 -Xlinker -dependency_info -Xlinker /Users/mac/Library/Developer/Xcode/DerivedData/test2-gghjzraszsaqbzbqxpuhzgopotmi/Build/Intermediates/test2.build/Release-iphoneos/test2.build/Objects-normal/arm64/test2_dependency_info.dat -o /Users/mac/Library/Developer/Xcode/DerivedData/test2-gghjzraszsaqbzbqxpuhzgopotmi/Build/Intermediates/test2.build/Release-iphoneos/test2.build/Objects-normal/arm64/test2
clang: error: no such file or directory: 'IQKeyboardManager'

**Comment by Ed-Dikotope** [comment]
Also waiting for the fix.

**Comment by EddyVerbruggen** [comment]
Had no issues with TNS 3.0 while developing #20. This can be closed once that's been merged.

**Comment by tjvantoll** [comment]
#20 has been merged and pushed out in version 1.1.0. If anyone is still hitting this problem please let us know.
