### ISSUE TITLE
[android] TabView items pushed up by the Keyboard

### ISSUE THREAD

**Issue by kefahB** [tjvantoll/nativescript-IQKeyboardManager#64]
Hi @tjvantoll, @EddyVerbruggen,

When the `IQKeyboardManager` is show the Tabview items is pushed up by the Keyboard, please see the image below 
<img width="1161" alt="Capture d’écran 2019-09-05 à 11 47 31" src="https://user-images.githubusercontent.com/18148534/64331561-4f7aae80-cfd3-11e9-9049-a9ba6e6dfe17.png">

**Comment by kefahB** [comment]
The `TabView` is the `root` and this page is a `Frame` on it.

**Comment by EddyVerbruggen** [comment]
This plugin enhances keyboard input for iOS only. There is nothing in here that should change how Android behaves.
