### ISSUE TITLE
[android] shouldResignOnTouchOutside not working

### ISSUE THREAD

**Issue by acortino** [tjvantoll/nativescript-IQKeyboardManager#65]
Hi,

I use your amazing plugin since the beginning of my project and everything is fine. 

I recently saw that the keyboard doesn't hide on touch outside (when it's working fine on iOS). I tried to update the plugin and it's still not working. 

(I still use NS 5.4.2)

Thanks in advance :)

**Comment by EddyVerbruggen** [comment]
This plugin enhances keyboard input for iOS only.
