### ISSUE TITLE
Placeholder (hint) for multi-line TextView not working

### ISSUE THREAD

**Issue by leocaseiro** [tjvantoll/nativescript-IQKeyboardManager#7]
Hi @tjvantoll, I'm not sure if is something with {N} or with the CocoaPod, but it seems my hints are not showing up when I use with [TextView](https://docs.nativescript.org/cookbook/ui/text-view). However, [TextField](https://docs.nativescript.org/cookbook/ui/text-field) work just fine.

Do you know if I'm doing something wrong?

Eq:

``` xml
<TextField hint="My textField" />  
<TextView hint="My textView" />
```

Thanks.

**Comment by tjvantoll** [comment]
@leocaseiro Sorry for the ridiculously late response here. This is related to https://github.com/tjvantoll/nativescript-IQKeyboardManager/issues/17, as it seems IQKeyboardManager only operates on UITextFields. 

Not sure what we can do about that as this is behavior of the CocoaPod itself. We do now expose the raw plugin typings, so you have a little more power to configure things (see https://github.com/tjvantoll/nativescript-IQKeyboardManager#advanced-usage).

I’m going to close this as I’m not sure what we can really do in this plugin, but if anyone stumbles upon this and has any ideas please comment.
