### ISSUE TITLE
fromework not found IQKeyboardManager

### ISSUE THREAD

**Issue by trevordowdle** [tjvantoll/nativescript-IQKeyboardManager#8]
After installing and running "tns prepare ios" when I try to build the application in xcode I get the following error:

Framework not found IQKeyboardManager
Link command failed

**Comment by trevordowdle** [comment]
Well with a little troubleshooting I did get it to work.  When preparing the app during installation I got the following warning "CocoaPods did not set the base configuration of your project because your project already has a customer config set..."  Above that there was a message "Please close any current Xcode sessions and use 'appname**.xcworkspace**' for this project from now on.

By opening the xcworkspace file and selecting/running the appropriate project I got it to work.

**Comment by kinggolf** [comment]
@trevordowdle Thanks for posting this. I started my 1st NativeScript project today and ran into exact same issue, so followed your findings and it worked. Cheers.
