### ISSUE TITLE
nativescript + Angular 2  IQKeyboardManager missing

### ISSUE THREAD

**Issue by alborozd** [tjvantoll/nativescript-IQKeyboardManager#9]
I use angular 2 and nativescript and I'd like to use IQKeyboardManager.
My steps:
1. Install cocoapods
2. run "pod setup" to setup cocapods
3. install plugin "tns plugin add nativescript-iqkeyboardmanager"
4. run app
And there is no iqkeyboardmanager in my application. Do I need do something else?

**Comment by Yamilquery** [comment]
Yes. You need to uninstall the app in IOS and redo a clean installation

**Comment by tjvantoll** [comment]
Sorry that we missed this issue when it came in :(

At this point all you need to do is `tns plugin add nativescript-iqkeyboardmanager` and `tns run ios`. If you’re still having issues please comment here and let us know.
